# Generated by Django 5.2 on 2025-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greetings', '0002_alter_task_status_category_task_categories_subtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'SubTask'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task'},
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('title', 'deadline')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'deadline')},
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('50%', '50%'), ('80%', '80%'), ('100%', '100%')], default='NEW', max_length=30),
        ),
        migrations.AlterModelTable(
            name='category',
            table='task_manager_category',
        ),
        migrations.AlterModelTable(
            name='subtask',
            table='task_manager_subtask',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task_manager_task',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='categories',
        ),
    ]
